import React from "react";

import gibson from "./images/gibson.png";
import guitarraelectrica from "./images/guitarraelectrica.png";
import guitarraelectricaprs from "./images/guitarraelectricaprs.png";
import ibanez from "./images/ibanez.png";
import lespaul from "./images/lespaul.png";
import vanhalen from "./images/vanhalen.png";
import bateria1tom from "./images/bateria1tom.png";
import bateria2bombo from "./images/bateria2bombo.png";
import bateria2tom from "./images/bateria2tom.png";
import bateria3tom from "./images/bateria3tom.png";
import bateria4tom from "./images/bateria4tom.png";
import bateria5tom from "./images/bateria5tom.png";
import bajogl from "./images/bajog&l.png";
import fender from "./images/fender.png";
import fenderviolet from "./images/fenderviolet.png";
import gl from "./images/g&l.png";
import ibanezbass from "./images/ibanezbass.png";
import ibanezbasses from "./images/ibanezbasses.png";
import korg from "./images/korg.png";
import montage from "./images/montage.png";
import motif from "./images/motif.png";
import nordstage from "./images/nordstage.png";
import roland from "./images/roland.png";
import roland2 from "./images/roland2.png";
import monitordb from "./images/monitordb.png";
import monitordbL from "./images/monitordbL.png";
import monitor from "./images/monitor.png";
import monitorL from "./images/monitorL.png";
import sidefill4 from "./images/sidefill4.png";
import sidefill4L from "./images/sidefill4L.png";
import sidefillarray from "./images/sidefillarray.png";
import sidefillarrayL from "./images/sidefillarrayL.png";
import sidefillpuntual from "./images/sidefillpuntual.png";
import sidefillpuntualL from "./images/sidefillpuntualL.png";
import sidefillt from "./images/sidefillt.png";
import sidefilltL from "./images/sidefilltL.png";
import sidetw from "./images/sidetw.png";
import sidetwL from "./images/sidetwL.png";
import substanitch from "./images/substanitch.png";
import substanitchL from "./images/substanitchL.png";
import c3500 from "./images/c3500.png";
import cl5 from "./images/cl5.png";
import sd10 from "./images/sd10.png";
import wings from "./images/wings.png";
import lv1 from "./images/lv1.png";
import mac from "./images/mac.png";
import corriente from "./images/snakes/corriente.png";
import s6l from "./images/s6l.png";
import sq6 from "./images/sq6.png";
import x32 from "./images/x32.png";
import snake8cha from "./images/snakes/snake8cha.png";
import soundtools from "./images/snakes/soundtools.png";
import snake12cha from "./images/snakes/snake12cha.png";
import directbox1 from "./images/directbox/directbox1.png";
import directbox2 from "./images/directbox/directbox2.png";
import directbox3 from "./images/directbox/directbox3.png";
import stand from "./images/rfmic/stand.png";
import stand1 from "./images/rfmic/stand1.png";
import stand2 from "./images/rfmic/stand2.png";
import mano from "./images/rfmic/mano.png";
import manoshure from "./images/rfmic/manoshure.png";
import sm58 from "./images/rfmic/sm58.png";
import antena1 from "./images/rfmic/antena1.png";
import antena from "./images/rfmic/antena.png";
import helicoidal from "./images/rfmic/helicoidal.png";
import antena1L from "./images/rfmic/antena1L.png";
import antenaL from "./images/rfmic/antenaL.png";
import helicoidalL from "./images/rfmic/helicoidalL.png";
import congadoble from "./images/Percu/congadoble.png";
import congadoble2 from "./images/Percu/congadoble2.png";
import accesorios from "./images/Percu/accesorios.png";
import bongo1 from "./images/Percu/bongo1.png";
import conga1 from "./images/Percu/conga1.png";
import conga2 from "./images/Percu/conga2.png";
import conga3 from "./images/Percu/conga3.png";
import block from "./images/Percu/block.png";
import bongo3 from "./images/Percu/bongo3.png";
import cajon1 from "./images/Percu/cajon1.png";
import cajon from "./images/Percu/cajon.png";
import saxofon from "./images/vientos/saxofon.png";
import trompeta from "./images/vientos/trompeta.png";
import trombom from "./images/vientos/trombom.png";
import chime from "./images/Percu/chime.png";
import cowbell from "./images/Percu/cowbell.png";
import darbuka from "./images/Percu/darbuka.png";
import djembe from "./images/Percu/djembe.png";
import djembe2 from "./images/Percu/djembe2.png";
import guira from "./images/Percu/guira.png";
import guira2 from "./images/Percu/guira2.png";
import guiro from "./images/Percu/guiro.png";
import hoopdrum from "./images/Percu/hoopdrum.png";
import maraca1 from "./images/Percu/maraca1.png";
import shaker from "./images/Percu/shaker.png";
import shekere from "./images/Percu/shekere.png";
import tambourine from "./images/Percu/tambourine.png";
import tambourine2 from "./images/Percu/tambourine2.png";
import timbal1 from "./images/Percu/timbal1.png";
import timbal2 from "./images/Percu/timbal2.png";
import triplebell from "./images/Percu/triplebell.png";
import moni from "./images/moni.png";
import monito from "./images/monito.png";
import monitoL from "./images/monitoL.png";
import peitsch from "./images/peitsch.png";
import side2 from "./images/side2.png";
import side2L from "./images/side2L.png";
import sonata from "./images/sonata.png";
import sonataL from "./images/sonataL.png";
import stanitchL from "./images/stanitchL.png";
import stanitch from "./images/stanitch.png";
import stsL from "./images/stsL.png";
import sts from "./images/sts.png";
import tuba from "./images/vientos/tuba.png";
import clarinete from "./images/vientos/clarinete.png";
import flauta from "./images/vientos/flauta.png";
import Charcheta from "./images/vientos/Charcheta-saxor-armonia.png";
import QUENA from "./images/vientos/QUENA.png";
import quena1 from "./images/vientos/quena1.png";
import saxoalto from "./images/vientos/saxoalto.png";
import saxosoprano from "./images/vientos/saxosoprano.png";
import saxotenor from "./images/vientos/saxotenor.png";
import SIKU from "./images/vientos/SIKU.png";
import SIKU2 from "./images/vientos/SIKU2.png";
import ZAMPOÑA from "./images/vientos/ZAMPOÑA.png";
import ÑOLKIN from "./images/vientos/ÑOLKIN.png";
import flauta3 from "./images/vientos/flauta3.png";
import trutuka from "./images/vientos/trutuka.png";
import armonica from "./images/vientos/armonica.png";
import PIFILKA from "./images/vientos/PIFILKA.png";
import zurdo from "./images/Percu/zurdo.png";
import TAMBORADOMINICANA from "./images/Percu/TAMBORADOMINICANA.png";
import tambores from "./images/Percu/tambores.png";
import PLATILLO from "./images/Percu/PLATILLO.png";
import hihat1 from "./images/Percu/hihat1.png";
import REDOBLANTE from "./images/Percu/REDOBLANTE.png";
import bomboleguero from "./images/Percu/bomboleguero.png";
import kultrum from "./images/Percu/kultrum.png";
import bateriaelectronica from "./images/Percu/bateriaelectronica.png";
import pezuñas from "./images/Percu/pezuñas.jpg";
import palodelluvia from "./images/Percu/palodelluvia.png";
import OCTAPAD from "./images/Percu/OCTAPAD.jpg";
import charango from "./images/cuerdas/charango.png";
import violin2 from "./images/cuerdas/violin2.png";
import violin1 from "./images/cuerdas/violin1.png";
import VIOLIN from "./images/cuerdas/VIOLIN.png";
import RONROCO from "./images/cuerdas/RONROCO.png";
import guitarra1 from "./images/cuerdas/guitarra1.png";
import guitarra from "./images/cuerdas/guitarra.png";
import cuatro from "./images/cuerdas/cuatro.png";
import ARPA from "./images/cuerdas/ARPA.png";
import ACORDEON from "./images/acordeon/ACORDEON.png";
import bandoneon1 from "./images/acordeon/bandoneon1.png";
import bandoneon from "./images/acordeon/bandoneon.png";
import acordeon1 from "./images/acordeon/acordeon1.png";
import palinear from "./images/palinear.png";
import palinearL from "./images/palinearL.png";
import sublinear from "./images/sublinear.png";
import sublinearL from "./images/sublinearL.png";
import silla from "./images/silla.png";
import accesorios1 from "./images/accesorios.png";
import solidrums from "./images/Percu/solidrums.png";
import solidrums2 from "./images/Percu/solidrums2.png";
import solidrums3 from "./images/Percu/solidrums3.png";
import TamboradegaitaZuliana from "./images/Percu/TamboradegaitaZuliana.png";
import tamboramexicana from "./images/Percu/tambora-mexicana.png";
import tamborescumaco from "./images/Percu/tamborescumaco.png";
import amplificador from "./images/directbox/amplificador.png";
import cajadirecta from "./images/directbox/cajadirecta.png";
import cajadirecta1 from "./images/directbox/cajadirecta1.png";
import spliter from "./images/directbox/spliter.png";
import fender1 from "./images/ampgtr/fender.png";
import marshall from "./images/ampgtr/marshall.png";
import vox from "./images/ampgtr/vox.png";
import orangepantalla from "./images/ampgtr/orangepantalla.png";
import orangecabezal from "./images/ampgtr/orangecabezal.png";
import gabinetemarshall from "./images/ampgtr/gabinetemarshall.png";
import cabezal from "./images/ampgtr/cabezal.png";
import ampegcabezal from "./images/ampbajo/ampegcabezal.png";
import aguilarcabezal from "./images/ampbajo/aguilarcabezal.png";
import ampegpantalla2 from "./images/ampbajo/ampegpantalla2.png";
import amphartec from "./images/ampbajo/amphartec.png";
import amphartec2 from "./images/ampbajo/amphartec2.png";
import ampmark from "./images/ampbajo/ampmark.png";
import ampegamp from "./images/ampbajo/ampegamp.png";
import ampegcmbo from "./images/ampbajo/ampegcmbo.png";
import ampegpantalla from "./images/ampbajo/ampegpantalla.png";
import GaetanoBC from "./images/ampbajo/GaetanoBC-150-bajo.png";
import GaetanoBT from "./images/ampbajo/Gaetano-bajo-BT-450.png";
import Apollo from "./images/ampgtr/Gaetano-Apollo-18-gtr.png";
import GTO from "./images/ampgtr/Gaetano-GTO-series-gtr.png";
import mandolinmandolina from "./images/cuerdas/mandolin-mandolina.png";
import Vihuela from "./images/cuerdas/Vihuela.png";
import guitarron from "./images/cuerdas/guitarron.png";
import Guitarra2 from "./images/cuerdas/Guitarra2.png";
import MANDOLINA from "./images/cuerdas/MANDOLINA.png";
import mr18 from "./images/mr18.png";
import Soundgraft from "./images/Soundgraft-ui24.png";
import corriente1 from "./images/corriente.png";
import BOMBOFOLCLORICO from "./images/Percu/BOMBOFOLCLORICO.png";
import BOMBOITALAQUE from "./images/Percu/BOMBOITALAQUE.png";
import ZAMPOÑACROMATICA from "./images/vientos/ZAMPOÑACROMATICA.png";
import tarka from "./images/tarka.png";
import MOSEÑO from "./images/vientos/MOSEÑO.png";
import pedal1 from "./images/ampbajo/pedal1.png";
import pedal2 from "./images/ampbajo/pedal2.png";
import pedal8 from "./images/ampbajo/pedal8.png";
import pedal11 from "./images/ampbajo/pedal11.png";
import pedal12 from "./images/ampbajo/pedal12.png";
import flecha from "./images/flecha.png";
import flecha1 from "./images/flecha1.png";
import flecha2 from "./images/flecha2.png";
import flecha3 from "./images/flecha3.png";
import flecha4 from "./images/flecha4.png";
import linea from "./images/linea.png";
import linea1 from "./images/linea1.png";
import linea2 from "./images/linea2.png";
import linea3 from "./images/linea3.png";
import linea4 from "./images/linea4.png";
import linea5 from "./images/linea5.png";
import tarima from "./images/tarima.png";
import tarima1 from "./images/tarima1.png";
import alfombra from "./images/alfombra.png";
import alfombra2 from "./images/alfombra2.png";
import multipin from "./images/multipin.png";
import pasacable from "./images/pasacable.png";
import mikra8 from "./images/sts/mikra8.png";
import mikra8L from "./images/sts/mikra8L.png";
import monitorsts from "./images/sts/monitor.png";
import monitorstsL from "./images/sts/monitorL.png";
import stsmoni from "./images/sts/sts.png";
import sts1 from "./images/sts/sts1.png";
import sts1L from "./images/sts/sts1L.png";
import substs from "./images/sts/sub.png";
import substsL from "./images/sts/subL.png";
import v7 from "./images/sts/v7.png";
import v7L from "./images/sts/v7L.png";
import v10 from "./images/sts/v10.png";
import v10L from "./images/sts/v10L.png";
import v101 from "./images/sts/v101.png";
import v101L from "./images/sts/v101L.png";
import v102 from "./images/sts/v102.png";
import v102L from "./images/sts/v102L.png";

//
const images = () => {
  return (
    <>
      <img src={v102} alt="foto" />
      <img src={v102L} alt="foto" />
      <img src={v101} alt="foto" />
      <img src={v101L} alt="foto" />
      <img src={v10} alt="foto" />
      <img src={v10L} alt="foto" />
      <img src={v7} alt="foto" />
      <img src={v7L} alt="foto" />
      <img src={substs} alt="foto" />
      <img src={substsL} alt="foto" />
      <img src={sts1} alt="foto" />
      <img src={sts1L} alt="foto" />
      <img src={stsmoni} alt="foto" />
      <img src={monitorsts} alt="foto" />
      <img src={monitorstsL} alt="foto" />
      <img src={mikra8L} alt="foto" />
      <img src={mikra8} alt="foto" />
      <img src={pasacable} alt="foto" />
      <img src={alfombra} alt="foto" />
      <img src={alfombra2} alt="foto" />
      <img src={multipin} alt="foto" />
      <img src={tarima1} alt="foto" />
      <img src={tarima} alt="foto" />
      <img src={linea5} alt="foto" />
      <img src={linea1} alt="foto" />
      <img src={linea2} alt="foto" />
      <img src={linea3} alt="foto" />
      <img src={linea4} alt="foto" />
      <img src={linea} alt="foto" />
      <img src={flecha1} alt="foto" />
      <img src={flecha2} alt="foto" />
      <img src={flecha3} alt="foto" />
      <img src={flecha4} alt="foto" />
      <img src={flecha} alt="foto" />
      <img src={pedal1} alt="foto" />
      <img src={pedal2} alt="foto" />
      <img src={pedal12} alt="foto" />
      <img src={pedal8} alt="foto" />
      <img src={pedal11} alt="foto" />
      <img src={MOSEÑO} alt="foto" />
      <img src={tarka} alt="foto" />
      <img src={ZAMPOÑACROMATICA} alt="foto" />
      <img src={BOMBOFOLCLORICO} alt="foto" />
      <img src={BOMBOITALAQUE} alt="foto" />
      <img src={corriente1} alt="foto" />
      <img src={Soundgraft} alt="foto" />
      <img src={mr18} alt="foto" />
      <img src={Guitarra2} alt="foto" />
      <img src={guitarron} alt="foto" />
      <img src={Vihuela} alt="foto" />
      <img src={MANDOLINA} alt="foto" />
      <img src={mandolinmandolina} alt="foto" />
      <img src={Apollo} alt="foto" />
      <img src={GTO} alt="foto" />
      <img src={GaetanoBT} alt="foto" />
      <img src={GaetanoBC} alt="foto" />
      <img src={ampegpantalla} alt="foto" />
      <img src={ampegcabezal} alt="foto" />
      <img src={ampegcmbo} alt="foto" />
      <img src={aguilarcabezal} alt="foto" />
      <img src={ampegamp} alt="foto" />
      <img src={ampegpantalla2} alt="foto" />
      <img src={amphartec} alt="foto" />
      <img src={amphartec2} alt="foto" />
      <img src={ampmark} alt="foto" />
      <img src={cabezal} alt="foto" />
      <img src={gabinetemarshall} alt="foto" />
      <img src={orangecabezal} alt="foto" />
      <img src={orangepantalla} alt="foto" />
      <img src={vox} alt="foto" />
      <img src={marshall} alt="foto" />
      <img src={fender1} alt="foto" />
      <img src={amplificador} alt="foto" />
      <img src={cajadirecta} alt="foto" />
      <img src={cajadirecta1} alt="foto" />
      <img src={spliter} alt="foto" />
      <img src={solidrums} alt="foto" />
      <img src={solidrums2} alt="foto" />
      <img src={solidrums3} alt="foto" />
      <img src={TamboradegaitaZuliana} alt="foto" />
      <img src={tamboramexicana} alt="foto" />
      <img src={tamborescumaco} alt="foto" />
      <img src={accesorios1} alt="foto" />
      <img src={silla} alt="foto" />
      <img src={ACORDEON} alt="foto" />
      <img src={bandoneon1} alt="foto" />
      <img src={bandoneon} alt="foto" />
      <img src={acordeon1} alt="foto" />
      <img src={ARPA} alt="foto" />

      <img src={VIOLIN} alt="foto" />
      <img src={violin1} alt="foto" />
      <img src={violin2} alt="foto" />
      <img src={OCTAPAD} alt="foto" />
      <img src={palodelluvia} alt="foto" />
      <img src={pezuñas} alt="foto" />
      <img src={bateriaelectronica} alt="foto" />
      <img src={palinear} alt="foto" />
      <img src={palinearL} alt="foto" />
      <img src={sublinear} alt="foto" />
      <img src={sublinearL} alt="foto" />
      <img src={sts} alt="foto" />
      <img src={stsL} alt="foto" />
      <img src={stanitch} alt="foto" />
      <img src={stanitchL} alt="foto" />
      <img src={sonataL} alt="foto" />
      <img src={sonata} alt="foto" />
      <img src={side2} alt="foto" />
      <img src={side2L} alt="foto" />
      <img src={peitsch} alt="foto" />
      <img src={monitoL} alt="foto" />
      <img src={monito} alt="foto" />
      <img src={moni} alt="foto" />
      <img src={triplebell} alt="foto" />
      <img src={timbal2} alt="foto" />
      <img src={timbal1} alt="foto" />
      <img src={tambourine2} alt="foto" />
      <img src={tambourine} alt="foto" />
      <img src={shekere} alt="foto" />
      <img src={shaker} alt="foto" />
      <img src={maraca1} alt="foto" />
      <img src={hoopdrum} alt="foto" />
      <img src={guiro} alt="foto" />
      <img src={guira2} alt="foto" />
      <img src={guira} alt="foto" />
      <img src={djembe2} alt="foto" />
      <img src={djembe} alt="foto" />
      <img src={darbuka} alt="foto" />
      <img src={cowbell} alt="foto" />
      <img src={chime} alt="foto" />
      <img src={trompeta} alt="foto" />
      <img src={trombom} alt="foto" />
      <img src={saxofon} alt="foto" />
      <img src={PIFILKA} alt="foto" />
      <img src={armonica} alt="foto" />
      <img src={trutuka} alt="foto" />
      <img src={ÑOLKIN} alt="foto" />
      <img src={ZAMPOÑA} alt="foto" />
      <img src={SIKU2} alt="foto" />
      <img src={SIKU} alt="foto" />
      <img src={saxotenor} alt="foto" />
      <img src={saxosoprano} alt="foto" />
      <img src={saxoalto} alt="foto" />
      <img src={quena1} alt="foto" />
      <img src={QUENA} alt="foto" />
      <img src={Charcheta} alt="foto" />
      <img src={flauta3} alt="foto" />
      <img src={flauta} alt="foto" />
      <img src={clarinete} alt="foto" />
      <img src={tuba} alt="foto" />
      <img src={cajon} alt="foto" />
      <img src={cajon1} alt="foto" />
      <img src={bongo3} alt="foto" />
      <img src={block} alt="foto" />
      <img src={conga3} alt="foto" />
      <img src={conga2} alt="foto" />
      <img src={conga1} alt="foto" />
      <img src={bongo1} alt="foto" />
      <img src={kultrum} alt="foto" />
      <img src={bomboleguero} alt="foto" />
      <img src={REDOBLANTE} alt="foto" />
      <img src={hihat1} alt="foto" />
      <img src={PLATILLO} alt="foto" />
      <img src={tambores} alt="foto" />
      <img src={TAMBORADOMINICANA} alt="foto" />
      <img src={zurdo} alt="foto" />
      <img src={accesorios} alt="foto" />
      <img src={congadoble2} alt="foto" />
      <img src={congadoble} alt="foto" />
      <img src={antena1} alt="foto" />
      <img src={antena} alt="foto" />
      <img src={helicoidal} alt="foto" />
      <img src={antena1L} alt="foto" />
      <img src={antenaL} alt="foto" />
      <img src={helicoidalL} alt="foto" />
      <img src={mano} alt="foto" />
      <img src={manoshure} alt="foto" />
      <img src={sm58} alt="foto" />
      <img src={stand} alt="foto" />
      <img src={stand1} alt="foto" />
      <img src={stand2} alt="foto" />
      <img src={directbox3} alt="foto" />
      <img src={directbox2} alt="foto" />
      <img src={directbox1} alt="foto" />
      <img src={snake12cha} alt="foto" />
      <img src={soundtools} alt="foto" />
      <img src={snake8cha} alt="foto" />
      <img src={x32} alt="foto" />
      <img src={sq6} alt="foto" />
      <img src={s6l} alt="foto" />
      <img src={corriente} alt="foto" />
      <img src={mac} alt="foto" />
      <img src={gibson} alt="foto" />
      <img src={guitarraelectrica} alt="foto" />
      <img src={guitarraelectricaprs} alt="foto" />
      <img src={ibanez} alt="foto" />
      <img src={lespaul} alt="foto" />
      <img src={vanhalen} alt="foto" />
      <img src={cuatro} alt="foto" />
      <img src={guitarra} alt="foto" />
      <img src={guitarra1} alt="foto" />
      <img src={RONROCO} alt="foto" />
      <img src={charango} alt="foto" />
      <img src={bateria1tom} alt="foto" />
      <img src={bateria2bombo} alt="foto" />
      <img src={bateria2tom} alt="foto" />
      <img src={bateria3tom} alt="foto" />
      <img src={bateria4tom} alt="foto" />
      <img src={bateria5tom} alt="foto" />
      <img src={bajogl} alt="foto" />
      <img src={fender} alt="foto" />
      <img src={fenderviolet} alt="foto" />
      <img src={gl} alt="foto" />
      <img src={ibanezbass} alt="foto" />
      <img src={ibanezbasses} alt="foto" />
      <img src={korg} alt="foto" />
      <img src={montage} alt="foto" />
      <img src={motif} alt="foto" />
      <img src={nordstage} alt="foto" />
      <img src={roland2} alt="foto" />
      <img src={roland} alt="foto" />
      <img src={monitordb} alt="foto" />
      <img src={monitordbL} alt="foto" />
      <img src={monitor} alt="foto" />
      <img src={monitorL} alt="foto" />
      <img src={sidefill4} alt="foto" />
      <img src={sidefill4L} alt="foto" />
      <img src={sidefillarray} alt="foto" />
      <img src={sidefillarrayL} alt="foto" />
      <img src={sidefillpuntual} alt="foto" />
      <img src={sidefillpuntualL} alt="foto" />
      <img src={sidefillt} alt="foto" />
      <img src={sidefilltL} alt="foto" />
      <img src={sidetw} alt="foto" />
      <img src={sidetwL} alt="foto" />
      <img src={substanitch} alt="foto" />
      <img src={substanitchL} alt="foto" />
      <img src={c3500} alt="foto" />
      <img src={cl5} alt="foto" />
      <img src={sd10} alt="foto" />
      <img src={wings} alt="foto" />
      <img src={lv1} alt="foto" />
    </>
  );
};

export default images;
